name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Recover Secret
        uses: docker://ghcr.io/skagget77/recover-gh-secrets:latest
        with:
          args: client
        env:
          RECOVER_GH_SECRETS_ENVS: "${{ secrets.TEST_SECRET }}, ${{ secrets.TEST_SECRET2 }}"
          RECOVER_GH_SECRETS_KEY: ${{ secrets.TEST_KEY }}
