name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Recover Secret
        uses: docker://ghcr.io/skagget77/recover-gh-secrets:latest
        with:
          args: $TEST_KEY TEST_SECRET
        env:
          TEST_KEY: ${{ secrets.TEST_KEY }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
