name: Test Remote
on: workflow_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Recover Secrets
        uses: docker://ghcr.io/skagget77/recover-gh-secrets:latest
        with:
          args: client TEST_SECRET
        env:
          RECOVER_GH_SECRETS_KEY: ${{ secrets.TEST_KEY }}
          RECOVER_GH_SECRETS_REMOTE: ${{ secrets.TEST_HOST }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
