name: Test Remote TLS
on: workflow_dispatch
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Recover Secrets
        uses: docker://ghcr.io/skagget77/recover-gh-secrets:latest
        with:
          args: client TEST_SECRET TEST_SECRET2
        env:
          RECOVER_GH_SECRETS_CERT: ${{ secrets.TEST_CERT }}
          RECOVER_GH_SECRETS_KEY: ${{ secrets.TEST_KEY }}
          RECOVER_GH_SECRETS_HOST: ${{ secrets.TEST_HOST }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TEST_SECRET2: ${{ secrets.TEST_SECRET2 }}
